# Generated by Django 5.2 on 2025-05-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.SmallIntegerField(choices=[(1, ''), (2, 'CHEVROLET - GM'), (3, 'AZUL'), (4, 'PRATA'), (5, 'PRETO'), (6, 'VERMELHO')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.TextField(max_length=5),
        ),
    ]
