# Generated by Django 5.2 on 2025-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0005_alter_veiculo_cor_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/fotos'),
        ),
    ]
