# Generated by Django 5.2 on 2025-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0007_alter_veiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/fotos'),
        ),
    ]
