# Generated by Django 5.2 on 2025-04-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.TextField(max_length=100),
        ),
    ]
