# Generated by Django 5.2 on 2025-05-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_alter_veiculo_cor_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.TextField(max_length=100),
        ),
    ]
