# Generated by Django 5.2 on 2025-05-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0004_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.SmallIntegerField(choices=[(1, 'AMARELO'), (2, 'BRANCO'), (3, 'AZUL'), (4, 'PRATA'), (5, 'PRETO'), (6, 'VERMELHO')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
    ]
